cookbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^user/', include('userauth.urls')),
    
    url(r'^news/', include('news.urls')),
    
    url(r'^', include('recipes.urls')),
 
	
)

news/urls.py
from django.conf.urls import patterns, include, url

from news.feeds import ArticleFeed
from news.views import ArticleDetailView, ArticleListView

urlpatterns = patterns('',
	url(r'^feed/rss/$', ArticleFeed(), name='news_article_feed'),
	url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), name='news_article_detail'),
	url(r'^$', ArticleListView.as_view(), name='news_article_list'),
)

recipes/urls.py
from django.conf.urls.defaults import patterns, include, url

from recipes.views import RecipeDetailView, RecipeListView

from recipes.api import RecipeResource
recipe_resource = RecipeResource()

urlpatterns = patterns('recipes.views',
    url(r'^add/$', 'add', name='recipes_recipe_add'),
    url(r'^edit/(?P<recipe_id>\d+)/$', 'edit', name='recipes_recipe_edit'),
)

urlpatterns += patterns('',
	url(r'^recipes/(?P<slug>[-\w]+)/$', RecipeDetailView.as_view(),
		name='recipes_recipe_detail'),
	url(r'^$', RecipeListView.as_view(), name='recipes_recipe_index'),
)

urlpatterns += patterns('',
	url(r'^api/', include(recipe_resource.urls)),
)

userauth/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

urlpatterns = patterns('django.contrib.auth.views',
	url(r'^login/$', 'login', {'template_name': 'userauth/login.html'},
		name='userauth_login'),
	url(r'^logout/$', 'logout', {'next_page': '/'},
		name='userauth_logout'),
		
	url(r'^password-change/$', 'password_change',
		{'template_name': 'userauth/password_change_form.html'},
		name='userauth_password_change'),
	url(r'^password-changed/$', 'password_change_done',
		{'template_name': 'userauth/password_change_done.html'},
		name='userauth_password_change_done'),
)
		
urlpatterns += patterns('',		
	url(r'^register/$', 'userauth.views.register',
		{'next_page_name': 'userauth_register_done'},
		name='userauth_register'),
	url(r'^welcome/$',
		TemplateView.as_view(template_name='userauth/register_done.html'),
		name='userauth_register_done'),
)

news/models.py
# encoding: utf-8
from django.db import models

from cookbook.basemodels import DateTimeInfo

class Article(DateTimeInfo):
	headline = models.CharField(u'Headline', max_length=100)
	body = models.TextField(u'Content')
	
	class Meta:
		verbose_name=u'Article'
		verbose_name_plural=u'Articles'
		ordering = ['-date_updated']
		
	def __unicode__(self):
		return self.headline

	@models.permalink
	def get_absolute_url(self):
		return ('news_article_detail', (), {'pk': self.pk})

recipes/models.py
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Category(models.Model):
	"""Category model."""
	name = models.CharField(u'Name', max_length=100)
	slug = models.SlugField(unique=True)
	description = models.TextField(u'Description', blank=True)

	class Meta:
		verbose_name = u'Category'
		verbose_name_plural = u'Categories'
		
	def __unicode__(self):
		return self.name

class ActiveRecipeManager(models.Manager):
	def get_query_set(self):
		return super(ActiveRecipeManager, self).get_query_set().filter(is_active=True)

class Recipe(models.Model):
	""" Recipe model. """
	is_active = models.BooleanField(u'Active')
	
	objects = models.Manager()
	active = ActiveRecipeManager()
	
	def get_related_recipes(self):
		categories = self.category.all()
		related_recipes = Recipe.active.all().filter(
			difficulty_exact=self.difficulty, category_in=categories)
		return related_recipes.exclude(pk=self.id).distinct()
	
	DIFFICULTY_EASY = 1
	DIFFICULTY_MEDIUM = 2
	DIFFICULTY_HARD = 3
	DIFFICULTIES = (
		(DIFFICULTY_EASY, u'easy'),
		(DIFFICULTY_MEDIUM, u'normal'),
		(DIFFICULTY_HARD, u'hard'),
	)
	title = models.CharField(u'Title', max_length=255)
	slug = models.SlugField(unique=True)
	ingredients = models.TextField(u'Ingredients',
		help_text = u'One ingredient per line')
	preparation = models.TextField(u'Preparation')
	time_for_preparation = models.IntegerField(u'Preparation Time',
		help_text = u'Specify time in minutes', blank=True, null=True)
	number_of_portions = models.PositiveIntegerField(u'Number of Portions')
	difficulty = models.SmallIntegerField(u'Difficulty',
		choices=DIFFICULTIES, default=DIFFICULTY_MEDIUM)
	category = models.ManyToManyField(Category, verbose_name=u'Categories')
	author = models.ForeignKey(User, verbose_name=u'Authors')
	date_created = models.DateTimeField(editable=False)
	date_updated = models.DateTimeField(editable=False)
	
	class Meta:
		verbose_name = u'Recipe'
		verbose_name_plural = u'Recipes'
		ordering = ['-date_created']
		
	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.id:
			self.date_created = now()
		self.date_updated = now()
		super(Recipe, self).save(*args, **kwargs)
		
	@models.permalink
	def get_absolute_url(self):
		return ('recipes_recipe_detail', (), { 'slug': self.slug })

userauth/models.py
from django.db import models

# Create your models here.

recipes/forms.py
from django.forms import ModelForm
from django.template.defaultfilters import slugify

from recipes.models import Recipe

class RecipeForm(ModelForm):
	class Meta:
		model = Recipe
		exclude = ('slug', 'author', 'date_created', 'date_updated')

	def __init__(self, **kwargs):
		self.__user = kwargs.pop('user', None)
		super(RecipeForm, self).__init__(**kwargs)
		
	def save(self, commit=True):
		if self.instance.pk is None:
			if self.__user is None:
				raise TypeError("You didn't give an user argument to the constructor.")
			self.instance.slug = slugify(self.instance.title)
			self.instance.author = self.__user
		return super(RecipeForm, self).save(commit)

news/views.py
from django.views.generic import DetailView, ListView

from news.models import Article

class ArticleDetailView(DetailView):
	model = Article
	
class ArticleListView(ListView):
	model = Article

recipes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.views.generic import DetailView, ListView

# Data models and forms
from recipes.models import Recipe
from recipes.forms import RecipeForm

# Logging
import logging
logger = logging.getLogger(__name__)

class RecipeListView(ListView):
	template_name = 'recipes/index.html'
	
	def get_queryset(self):
		recipes = Recipe.active.all()
		logger.debug('Number of Recipes: %d' % recipes.count())
		return recipes
		
class RecipeDetailView(DetailView):
	queryset = Recipe.active.all()
	template_name = 'recipes/detail.html'


def detail(request, slug):
	recipe = get_object_or_404(Recipe, slug=slug)
	return render(request, 'recipes/detail.html', 
		{'object': recipe})
		
@login_required
def add(request):
	if request.method == 'POST':
		form = RecipeForm(user=request.user, data=request.POST)
		if form.is_valid():
			recipe=form.save()
			return HttpResponseRedirect(recipe.get_absolute_url())
	else:
		form = RecipeForm()
	return render(request, 'recipes/form.html',
		{'form': form, 'add': True})

@login_required
def edit(request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	if recipe.author != request.user and not request.user.is_staff:
		return HttpResponseForbidden()
	if request.method == 'POST':
		form = RecipeForm(instance=recipe, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(recipe.get_absolute_url())
	else:
		form = RecipeForm(instance=recipe)
	return render(request, 'recipes/form.html',
		{'form': form, 'add': False, 'object': recipe})

userauth/views.py
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

def register(request, template_name='userauth/register.html', next_page_name=None):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			if next_page_name is None:
				next_page = '/'
			else:
				next_page=reverse(next_page_name)
			return HttpResponseRedirect(next_page)
	else:
		form = UserCreationForm()
	return render_to_response(template_name, {'form': form},
		context_instance=RequestContext(request))

news/templates/news/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - {{ article.headline }} {% endblock %}

{% block content %}
<h4> {{ article.headline }} </h4>
<p>{{ article.date_updated }}</p>
<p>{{ article.body }}</p>
{% endblock %}

news/templates/news/article_list.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - News{% endblock %}

{% block content %}
<ul>
{% for article in article_list %}
	<li>
		<h4><a href='{{ article.get_absolute_url }}'>{{ article.headline }}</a></h4>
		<p>{{ article.date_updated }}</p>
		<p>{{ article.body }}</p>
	</li>
{% endfor %}
</ul>
{% endblock %}

recipes/templates/recipes/detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - {{ object.title }}{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>
<a href="{% url recipes_recipe_index %}">Return to Overview</a>

<a href="{% url recipes_recipe_edit object.pk %}">Edit Recipe</a>

<p> {{ object.number_of_portions }} 
	Portion{{ object.number_of_portions|pluralize:"en" }}.</p>
<h3>Ingredients</h3>
{{ object.ingredients|linebreaks }}
<h3>Preparation</h3>
{{ object.preparation|linebreaks }}
<p>Preparation time: {{ object.time_for_preparation }} minutes</p>

<p>Difficulty: {{ object.get_difficulty_display }}</p>
<p>Author: {{ object.author }}</p>

<h4>Category{{ object.category.count|pluralize:"ies" }}</h4>
<ul>
	{% for category in object.category.all %}
		<li>{{ category.name }}</li>
	{% endfor %}
	
</ul>
{% endblock %}

recipes/templates/recipes/form.html
{% extends 'base.html' %}

{% block title %}
{{ block.super}} - Recipe {% if add %}Add
	{% else %}"{{ object.title }}" edit{% endif %}
{% endblock %}

{% block content %}
{% if add %}
<h2>Add Recipe</h2>
{% url recipes_recipe_add as action_url %}
{% else %}
<h2>Recipe "{{ object.title }}" edit</h2>
{% url recipes_recipe_edit object.pk as action_url %}
{% endif %}
<form action="{{ action_url }}" method="post"  accept-charset="utf-8">
	{{ form.as_p }}
	{% csrf_token %}
	<p><input type='submit' value='Save'</p>
</form>
<a href="{% url recipes_recipe_index %}">Back to List</a>
{% endblock %}

recipes/templates/recipes/index.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - All Recipes{% endblock %}

{% block content %}
<h2>All Recipes</h2>
<a href="{% url recipes_recipe_add %}">Add Recipe</a>
<ul>
	{% for recipe in object_list %}
	<li><a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a></li>
	{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset='utf-8'>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Cookbook{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <script src="{{ STATIC_URL }}js/vendor/modernizr-2.6.2.min.js"></script>
        
	<!-- RSS Feed -->
	<link rel='alternate' type='application/rss+xml' title='News from the Cookbook' href='{% url news_article_feed %}' />
</head>
<body>
	<!--[if lt IE 7]>
           <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    </header>
	<h1>Cookbook</h1>
	{% block toggle_login %}
		{% include 'userauth/toggle_login.html' %}
	{% endblock %}
	</header>
	<div role='main'>
	{% block content %}{% endblock %}
	</div>
	
	<footer>
	
	</footer>
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.8.2.min.js"><\/script>')</script>
        <script src="{{ STATIC_URL }}js/plugins.js"></script>
        <script src="{{ STATIC_URL }}js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
	
</body>
</html>

userauth/templates/userauth/login.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Login{% endblock %}

{% block toggle_login %}{% endblock %}

{% block content %}
	<form action='{% url userauth_login %}' method='post' accept-charset='utf-8'>
		{{ form.as_p }}
		{% csrf_token %}
		<input type='hidden' name='next' value='{{ next }}' />
		<input type='submit' value='Login' />
	</form>
{% endblock %}

userauth/templates/userauth/password_change_done.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Password Changed Done{% endblock %}

{% block content %}
<p>Your password was changed successfully.</p>
<a href='{% url recipes_recipe_index %}'>Back to list</a>
{% endblock %}

userauth/templates/userauth/password_change_form.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Password Change{% endblock %}

{% block toggle_login %}{% endblock %}

{% block content %}
<form action='{% url userauth_password_change %}' method='post' accept-charset='utf-8'>
	{{ form.as_p }}
	{% csrf_token %}
	<input type='submit' value='password change' />
</form>
{% endblock %}

userauth/templates/userauth/register.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Register{% endblock %}

{% block toggle_login %}{% endblock %}

{% block content %}
<form action='{% url userauth_register %}' method='post' accept-charset='utf-8'>
	{{ form.as_p }}
	{% csrf_token %}
	<input type='submit' value='register' />

</form>
{% endblock %}

userauth/templates/userauth/register_done.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Registration successful!{% endblock %}

{% block content %}
<p> You're registered.  Have fun the the cookbook! </p>
<a href='{% url recipes_recipe_index %}'>Back to Overview</a>
{% endblock %}

userauth/templates/userauth/toggle_login.html
{% if user.is_authenticated %}
	<p>Hi {{ user.username }}!
	<a href='{% url userauth_password_change %}'>Change Password</a>
	<a href='{% url userauth_logout %}'>Logout</a></p>
{% else %}
	<p><a href='{% url userauth_login %}'>Login</a>
	<a href='{% url userauth_register %}'>Register</a></p>
{% endif %}